# Don't forget to lint changes to this file: http://lint.travis-ci.org/
# For help see http://docs.travis-ci.com/user/build-configuration/
# All commands must exit with code 0 on success, or considered failure.

language: python
python:
  - 2.7
  - 3.4

# Which branch commits to build and test on.
branches:
  only:
    - master

# PREPARE SYSTEM to install prerequisites or dependencies.
before_install:
  - sudo apt-get update
  # - sudo apt-get -y upgrade
  # - sudo apt-get -y -qq install [packages]

# INSTALL prerequisites or dependencies necessary to run your build.
install:
  # - pip install -r requirements.txt
  - pip install coveralls

# PREPARE BUILD for testing, e.g. database config, env_vars
# before_script:

# RUN tests, and get coverage stats.
script:
  # - python setup.py test
  - coverage run --source=getcrackin setup.py test

# Results exported to TRAVIS_TEST_RESULT, use in after_script commands.
# Send off coverage info to coveralls.io.
after_script:
  - coveralls

