# Don't forget to lint changes to this file: http://lint.travis-ci.org/
# For help see http://docs.travis-ci.com/user/build-configuration/
# All commands must exit with code 0 on success, or considered failure.

language: python
python:
  - 3.4
  - 2.7

# Which branch commits to build and test on.
branches:
  only:
    - master

# PREPARE SYSTEM to install prerequisites or dependencies.
before_install:
  - travis_wait apt-get -qq update
  - travis_wait apt-get -y -qq upgrade
  # - sudo apt-get -y -qq install [packages]

# INSTALL prerequisites or dependencies necessary to run your build.
# install:
#   - pip install -r requirements.txt

# PREPARE BUILD for testing, e.g. database config, env_vars
# before_script:

# RUN tests, e.g. python setup.py test.
script:
  - python setup.py test

# Result exported to TRAVIS_TEST_RESULT, you can use in after_script commands.
# after_script:

